// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TestAssignmentAvSoft.Infrastructure;

namespace TestAssignmentAvSoft.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TestAssignmentAvSoft.Models.CounterModel", b =>
                {
                    b.Property<Guid>("Guid")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Id");

                    b.Property<int>("Value");

                    b.HasKey("Guid");

                    b.ToTable("Counters");

                    b.HasData(
                        new { Guid = new Guid("2475094d-3975-40ff-9782-b9d4cd09ef6b"), Id = 1, Value = 1 },
                        new { Guid = new Guid("ca630fce-083e-4d28-a646-9ba8677035f3"), Id = 1, Value = 2 },
                        new { Guid = new Guid("e38c4443-4a30-4b1d-ac24-ffa7ba89e209"), Id = 1, Value = 3 },
                        new { Guid = new Guid("58799f87-519e-460d-bc94-33fa6eff2e6c"), Id = 2, Value = 1 },
                        new { Guid = new Guid("1e8239d2-518c-42b9-9637-33308b0dc814"), Id = 2, Value = 1 },
                        new { Guid = new Guid("837997c9-7b48-4fe3-b700-604c9534b046"), Id = 2, Value = 3 },
                        new { Guid = new Guid("3fb1ce83-8661-4bc7-95ef-3c6bd5129269"), Id = 2, Value = 1 }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
